export enum EstadoCaso {
  REGISTRADO = 'REGISTRADO',
  ASIGNADO = 'ASIGNADO',
  EN_PROCESO = 'EN_PROCESO',
  EN_DERIVACION = 'EN_DERIVACION',
  EN_ESPERA_SOLICITANTE = 'EN_ESPERA_SOLICITANTE',
  ESCALADO = 'ESCALADO',
  RESUELTO = 'RESUELTO',
  CERRADO_CONFORME = 'CERRADO_CONFORME',
  REABIERTO = 'REABIERTO',
  RECHAZADO_ORIGEN = 'RECHAZADO_ORIGEN'
}

export enum PrioridadCaso {
  BAJA = 'BAJA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA',
  URGENTE = 'URGENTE',
  CRITICA_INSTITUCIONAL = 'CRITICA_INSTITUCIONAL'
}

export enum TipoNovedad {
  OBSERVACION = 'OBSERVACION',
  AVANCE = 'AVANCE',
  INCIDENCIA = 'INCIDENCIA',
  COMPROMISO = 'COMPROMISO',
  INSTRUCCION = 'INSTRUCCION',
  RESPUESTA = 'RESPUESTA',
  CAMBIO_ESTADO = 'CAMBIO_ESTADO',
  DERIVACION = 'DERIVACION',
  BLOQUEO = 'BLOQUEO',
  RESULTADO = 'RESULTADO',
  SEGUIMIENTO = 'SEGUIMIENTO'
}

export enum EstadoDerivacion {
  SOLICITADA = 'SOLICITADA',
  ACEPTADA = 'ACEPTADA',
  RECHAZADA = 'RECHAZADA',
  CONCLUIDA = 'CONCLUIDA'
}

export enum NivelVisibilidad {
  COMUNICACION_SOLICITANTE = 'COMUNICACION_SOLICITANTE',
  COMUNICACION_INTERNA = 'COMUNICACION_INTERNA',
  NOTA_PRIVADA = 'NOTA_PRIVADA'
}

export enum RolInstitucional {
  SOLICITANTE = 'SOLICITANTE',
  FUNCIONARIO_TECNICO = 'FUNCIONARIO_TECNICO',
  SUPERVISOR_UNIDAD = 'SUPERVISOR_UNIDAD',
  DIRECTOR = 'DIRECTOR',
  SUBALCALDE = 'SUBALCALDE',
  AUTORIDAD_INSTITUCIONAL = 'AUTORIDAD_INSTITUCIONAL',
  AUDITOR_INTERNO = 'AUDITOR_INTERNO',
  ADMINISTRADOR_FUNCIONAL = 'ADMINISTRADOR_FUNCIONAL'
}

export enum TipoDependencia {
  DESPACHO = 'DESPACHO',
  SECRETARIA = 'SECRETARIA',
  DIRECCION = 'DIRECCION',
  UNIDAD = 'UNIDAD',
  DEPARTAMENTO = 'DEPARTAMENTO',
  PROGRAMA_EQUIPO = 'PROGRAMA_EQUIPO',
  SUBALCALDIA = 'SUBALCALDIA'
}

export enum NivelSensibilidad {
  OPERATIVA = 'OPERATIVA',
  ADMINISTRATIVA = 'ADMINISTRATIVA',
  PERSONAL = 'PERSONAL',
  CONFIDENCIAL_SENSIBLE = 'CONFIDENCIAL_SENSIBLE',
  AUDITORIA = 'AUDITORIA'
}
